#' @keywords internal
"_PACKAGE"

# Suppress R CMD check NOTEs for dplyr/tidyr NSE column references
utils::globalVariables(c(
  ".pk_row_id",
  "aberr_norm",
  "aberr_raw",
  "aberrations",
  "a_seg",
  "autosomal_monosomies_sample",
  "b_chrom",
  "b_seg",
  "balanced_pair",
  "bb1",
  "bb2",
  "bp_a",
  "bp_b",
  "bracket",
  "chrom",
  "chromosome_count",
  "cleaned",
  "clone_id",
  "clone_str",
  "comma_count_aberrations",
  "content",
  "der_inner",
  "donor",
  "donor_is_p1",
  "first_is_sex",
  "first_token",
  "flag",
  "flag_name",
  "has_idem",
  "head",
  "issue_type",
  "is_composite",
  "is_cp",
  "is_der",
  "is_mono_tri",
  "is_range_karyotype",
  "fixable_error",
  "unfixable_error",
  "max_count",
  "mixed_ploidy",
  "monosomal_karyotype",
  "n",
  "n_unique_aberr",
  "normal_karyotype",
  "p1",
  "p2",
  "preprocessed_karyotype",
  "original_karyotype",
  "ploidy_result",
  "prefix",
  "raw",
  "raw_comma_count",
  "row_index",
  "seg",
  "stemline_aberr_count",
  "structural_aberrations_sample",
  "swap",
  "t_b1",
  "t_b2",
  "t_c1",
  "t_c2",
  "t_sig",
  "tokens_nonempty",
  "total_metaphases",
  "value"
))


# ---- Constants ---------------------------------------------------------------
.karyoparser_version <- as.character(utils::packageVersion("karyoparser"))

.sex_complements <- c(
  "X",
  "Y",
  "XX",
  "XY",
  "XXX",
  "XXY",
  "XYY",
  "XXYY",
  "XXXY",
  "XXXX",
  "XXXXY"
)
